language: c

os:
  - linux
  - osx
  
env:
 - CABALVER=1.18;
 - GHCVER=7.8.3;
 
install:
    - echo $TRAVIS_OS_NAME
    - case "$TRAVIS_OS_NAME" in
    
       "linux")
         echo "constraints:async==2.0.1.5,attoparsec==0.10.4.0,case-insensitive==1.1.0.3,fgl==5.5.0.1,GLUT==2.5.1.1,GLURaw==1.4.0.1,haskell-src==1.0.1.6,hashable==1.2.2.0,html==1.0.1.2,HTTP==4000.2.10,HUnit==1.2.5.2,mtl==2.1.3.1,network==2.4.2.3,OpenGL==2.9.2.0,OpenGLRaw==1.5.0.0,parallel==3.2.0.4,parsec==3.1.5,primitive==0.5.2.1,QuickCheck==2.6,random==1.0.1.1,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.2,stm==2.4.2,syb==0.4.1,text==1.1.0.0,transformers==0.3.0.0,unordered-containers==0.2.4.0,vector==0.10.9.1,xhtml==3000.2.1,zlib==0.5.4.1" > cabal.config ;
         sudo add-apt-repository -y ppa:hvr/ghc;
         sudo apt-get update;
         sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER;
         export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH;
         cabal --version;
         cabal install idris;;
         
       "osx")
         brew install idris;;
         
      esac
      
script:
    - idris --build helloWorld.ipkg

after_script:
    ./helloWorld
