language: haskell

matrix:
  include:
    - os: 
        - linux
      ghc:
        - 7.8
    - os:
        - osx


install:
    - echo $TRAVIS_OS_NAME
    - sudo apt-get update -qq
    - if [ "$TRAVIS_OS_NAME == osx" ]; then brew install idris; fi
    - if [ "$TRAVIS_OS_NAME == linux" ]; then cabal install idris; fi

script:
    - idris --build helloWorld.ipkg

after_script:
    ./helloWorld
